version: '3.8'

services:
  mysql-onprem:
    image: mysql:8.0
    container_name: dba-mysql-lab
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dba2024!
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: dba_user
      MYSQL_PASSWORD: dba_pass
    ports:
      - "3306:3306"
    volumes:
      # Datos persistentes
      - mysql_data:/var/lib/mysql
      # Scripts de inicializaci칩n
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      # Datasets para laboratorios
      - ../../04-datasets:/datasets:ro
      # Configuraci칩n personalizada
      - ./config/my.cnf:/etc/mysql/conf.d/dba-custom.cnf:ro
      # Logs para an치lisis
      - mysql_logs:/var/log/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
      --log-error=/var/log/mysql/error.log
      --innodb-buffer-pool-size=512M
      --max-connections=200
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdba2024!"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

  # Herramientas adicionales para DBA
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dba-mysql-admin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-onprem
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: dba2024!
    ports:
      - "8080:80"
    depends_on:
      mysql-onprem:
        condition: service_healthy

  # Monitoring b치sico
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: dba-mysql-monitor
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "dba_user:dba_pass@(mysql-onprem:3306)/"
    ports:
      - "9104:9104"
    depends_on:
      mysql-onprem:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local

networks:
  default:
    name: dba-lab-network
