version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: escenario-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: training_db
    ports:
      - "27017:27017"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db-network

  simulator:
    build: ./simuladores
    container_name: escenario-simulator
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb
      DB_USER: admin
      DB_PASS: admin123
      DB_NAME: training_db
    networks:
      - db-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - db-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - db-network

  mongodb-exporter:
    image: percona/mongodb_exporter:latest
    container_name: mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
