version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: escenario-03-locks-postgres
    environment:
      POSTGRES_DB: training_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db-network

  simulator:
    build: ./simuladores
    container_name: escenario-03-locks-simulator
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_USER: app_user
      DB_PASS: app_pass
      DB_NAME: training_db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
