version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: escenario-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dba2024!
      MYSQL_DATABASE: training_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - backup_volume:/backup
    networks:
      - db-network

  simulator:
    build: ./simuladores
    container_name: escenario-simulator
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: app_user
      DB_PASS: app_pass
      DB_NAME: training_db
    volumes:
      - backup_volume:/backup
    networks:
      - db-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - db-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - db-network

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=app_user:app_pass@(mysql-db:3306)/training_db
    depends_on:
      - mysql-db
    networks:
      - db-network

volumes:
  mysql_data:
  backup_volume:

networks:
  db-network:
    driver: bridge
